name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install Python deps
        shell: bash
        run: pip3 install numpy matplotlib

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: bash run_tests.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ndk-plots
          path: "*.png"
